name: sqflow_core
description: A flexible CRUD service for SQLite in Flutter/Dart with soft delete, advanced querying (WhereBuilder), sorting, and schema management.
version: 1.0.0
homepage: https://github.com/interdev7/sqflow_core
repository: https://github.com/interdev7/sqflow_core
issue_tracker: https://github.com/interdev7/sqflow_core/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.2+1

# Publication to pub.dev
publish_to: none
